### ISSUE TITLE
/bin/bash: del: command not found

### ISSUE THREAD

**Issue by carlacwinter1** [vsnnlab/AMaSiNe#2]
Hi there,

Thanks so much for providing this useful set of code! 

I'm currently going through the tutorial with the example images you provide, but I'm running into an issue once I get to STEP_4 and beyond. When I try to run STEP_4 (and STEP_5), I get an error saying "/bin/bash: del: command not found". 

```>> STEP_4_Angle_Finder
/bin/bash: del: command not found
/bin/bash: del: command not found
STAGE 1 : Contrast Adjustment and AP Positioning
    {'   Stage 1   :   252.6124  seconds   '}

Searching Stage 2 - Find Angles: Angle Resolution =8
Starting parallel pool (parpool) using the 'local' profile ...
```

Despite this error, STEP_4 completes and creates the "Step_4_Angle_Search_Result.mat" file, I get no errors for Step_4to5, but then again get this same error during STEP_5. However, unlike STEP_4, STEP_5 quits itself.

I assume this is stemming from Elastix not being loaded properly into my system path. I am working on a Mac, and have added Elastix to the Path via the following in my terminal:

`
(base) dhcp-10-29-247-182:~ carlawinter$ echo $PATH
/opt/miniconda3/bin:/opt/miniconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Library/Apple/usr/bin
(base) dhcp-10-29-247-182:~ carlawinter$ PATH_BACKUP=$PATH
(base) dhcp-10-29-247-182:~ carlawinter$ PATH=$PATH_BACKUP:/Users/carlawinter/Image_Analysis/Elastix/elastix-5.0.0-mac
(base) dhcp-10-29-247-182:~ carlawinter$ echo $PATH
/opt/miniconda3/bin:/opt/miniconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Library/Apple/usr/bin:/Users/carlawinter/Image_Analysis/Elastix/elastix-5.0.0-mac
`

So based on this, I think Elastix is correctly added to my system path. So I'm not sure where my error messages are coming from.

Any insight you have would be greatly appreciated. Thanks!

**Comment by carlacwinter1** [comment]
Attached here is the full command output with errors:

[command output.pdf](https://github.com/vsnnlab/AMaSiNe/files/6086405/command.output.pdf)

**Comment by carlacwinter1** [comment]
RESOLVED:
- Don't use Mac OS
- Don't put a space in your computer's username or profile folder

**Comment by LWitter** [comment]
Did you get it to work in the end on Mac OS, or is it just a no-go?
If Mac OS doesn't work, I'll have to think of another solution. So I hope there is a work-around.....

**Comment by carlacwinter1** [comment]
I couldn't get it to work on a Mac. I believe "del" (where I was having initial error) is a windows command

You could partition Windows on your Mac with bootcamp

**Comment by mdeutsch22** [comment]
I forgot to mention that I was able to run elastix with Matlab by disabling the SIP in the recovery mode, adding the elastix PATH to .bashirsc and running Matlab with the terminal. (And enabling SIP again) However, this didn't resolve the del issue and I got the same error : Error using 

> Error using STEP_5_Transform_and_ROI_drawing (line 66)
> The source code
> (/Users/matthias/Documents/MATLAB/AMaSiNe/Amasine_test/STEP_5_Transform_and_ROI_drawing.m)
> for the parfor-loop that is trying to execute on the worker could not be found.
> 
> Caused by:
>     Unrecognized function or variable 'matched_img'.
>     Error using remoteParallelFunction (line 84)
>     Worker unable to find file.
>         Unrecognized function or variable 'matched_img'.

**Comment by menage95** [comment]
Hey everyone, 

I am also having the same issue (doesn't work on M1 mac) and now using a windows machine but I'm getting the matched image error message on step 5: 


Error using STEP_5_Transform_and_ROI_drawing
The source code (C:\AMaSiNe-master\STEP_5_Transform_and_ROI_drawing.m) for the parfor-loop that is trying to
execute on the worker could not be found.

Caused by:
    Unrecognized function or variable 'matched_img'.
    Error using remoteParallelFunction
    Worker unable to find file.
        Unrecognized function or variable 'matched_img'.

How exactly did you fix this? 

Thanks,
Lucy
